services:
  workshop:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: workshop
    restart: unless-stopped
    env_file: .env
    ports:
      - "8080:4000"
    volumes:
      - ./lessons:/home/node/workshop
      - node_modules:/home/node/app/node_modules
    networks:
      - workshop-network

networks:
  workshop-network:
    driver: bridge

volumes:
  node_modules: 